import esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const isProduction = process.env.NODE_ENV === 'production';
const isWatch = process.argv.includes('--watch');

const buildOptions = {
  entryPoints: [join(__dirname, '../src/client/modal/index.js')],
  bundle: true,
  outfile: join(__dirname, '../src/client/build/modal.bundle.js'),
  format: 'iife',
  target: 'es2017',
  minify: isProduction,
  sourcemap: !isProduction,
  banner: {
    js: '// Salla Bundle Modal - Generated Bundle\n// Do not edit this file directly\n',
  },
};

if (isWatch) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
  console.log('👀 Watching for changes...');
} else {
  try {
    await esbuild.build(buildOptions);
    console.log('✅ Modal bundle built successfully!');
    console.log(`   Output: ${buildOptions.outfile}`);
    console.log(`   Mode: ${isProduction ? 'production' : 'development'}`);
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}


